import type {
  Account,
  Agent,
  AIConfig,
  AIAgent,
  Comment,
  Conversation,
  Customer,
  CustomerTag,
  DashboardStats,
  KnowledgeCategory,
  KnowledgeDocument,
  Platform,
  ScriptTemplate,
} from "@/types";

// ===== 客服团队 =====
export const mockAgents: Agent[] = [
  {
    id: "agent_1",
    name: "张小明",
    avatar: "",
    role: "admin",
    status: "online",
    maxConcurrent: 20,
    activeConversations: 8,
    email: "zhangxm@zhike.com",
    phone: "13800138001",
    department: "客服一部",
    onlineSince: "2026-06-17T08:00:00Z",
  },
  {
    id: "agent_2",
    name: "李婷婷",
    avatar: "",
    role: "supervisor",
    status: "online",
    maxConcurrent: 15,
    activeConversations: 5,
    email: "litt@zhike.com",
    phone: "13800138002",
    department: "客服一部",
    onlineSince: "2026-06-17T09:00:00Z",
  },
  {
    id: "agent_3",
    name: "王大力",
    avatar: "",
    role: "agent",
    status: "busy",
    maxConcurrent: 10,
    activeConversations: 10,
    email: "wangdl@zhike.com",
    phone: "13800138003",
    department: "客服二部",
    onlineSince: "2026-06-17T08:30:00Z",
  },
  {
    id: "agent_4",
    name: "赵雪儿",
    avatar: "",
    role: "agent",
    status: "online",
    maxConcurrent: 10,
    activeConversations: 3,
    email: "zhaoxe@zhike.com",
    phone: "13800138004",
    department: "客服二部",
    onlineSince: "2026-06-17T10:00:00Z",
  },
  {
    id: "agent_5",
    name: "陈思远",
    avatar: "",
    role: "agent",
    status: "away",
    maxConcurrent: 10,
    activeConversations: 0,
    email: "chensy@zhike.com",
    department: "客服三部",
  },
  {
    id: "agent_6",
    name: "刘佳佳",
    avatar: "",
    role: "agent",
    status: "offline",
    maxConcurrent: 10,
    activeConversations: 0,
    email: "liujj@zhike.com",
    department: "客服三部",
  },
];

// ===== 账号 =====
export const mockAccounts: Account[] = [
  {
    id: "acc_1",
    name: "智客教育官方",
    avatar: "",
    platform: "xiaohongshu",
    platformUid: "xhs_001",
    followers: 128000,
    status: "online",
    assignedAgentId: "agent_1",
  },
  {
    id: "acc_2",
    name: "智客教育-考研",
    avatar: "",
    platform: "xiaohongshu",
    platformUid: "xhs_002",
    followers: 56000,
    status: "online",
    assignedAgentId: "agent_2",
  },
  {
    id: "acc_3",
    name: "智客教育课堂",
    avatar: "",
    platform: "douyin",
    platformUid: "dy_001",
    followers: 890000,
    status: "online",
    assignedAgentId: "agent_3",
  },
  {
    id: "acc_4",
    name: "智客教育直播号",
    avatar: "",
    platform: "douyin",
    platformUid: "dy_002",
    followers: 230000,
    status: "offline",
  },
  {
    id: "acc_5",
    name: "智客教育-留学",
    avatar: "",
    platform: "kuaishou",
    platformUid: "ks_001",
    followers: 45000,
    status: "online",
    assignedAgentId: "agent_4",
  },
];

// ===== 客户标签 =====
export const mockTags: CustomerTag[] = [
  { id: "tag_1", name: "高意向", color: "#EF4444" },
  { id: "tag_2", name: "已留资", color: "#10B981" },
  { id: "tag_3", name: "考研", color: "#3B82F6" },
  { id: "tag_4", name: "留学", color: "#8B5CF6" },
  { id: "tag_5", name: "K12", color: "#F59E0B" },
  { id: "tag_6", name: "待跟进", color: "#6B7280" },
  { id: "tag_7", name: "已购课", color: "#06B6D4" },
  { id: "tag_8", name: "退款意向", color: "#EC4899" },
];

// ===== 客户 =====
export const mockCustomers: Customer[] = [
  {
    id: "cus_1",
    name: "学习达人小美",
    avatar: "",
    platform: "xiaohongshu",
    platformUid: "xhs_user_001",
    phone: "139****8888",
    wechat: "xm_study",
    status: "following",
    leadStatus: "leaded",
    tags: ["tag_1", "tag_2", "tag_3"],
    note: "对考研英语冲刺班很感兴趣，预算5000以内",
    source: "聚光广告-考研英语",
    firstContactAt: "2026-06-15T10:30:00Z",
    lastContactAt: "2026-06-17T15:10:00Z",
    totalMessages: 28,
    intentLevel: "high",
  },
  {
    id: "cus_2",
    name: "努力上岸的阿杰",
    avatar: "",
    platform: "xiaohongshu",
    platformUid: "xhs_user_002",
    status: "new",
    leadStatus: "not_leaded",
    tags: ["tag_3", "tag_6"],
    note: "咨询了考研政治课程，但未留下联系方式",
    source: "自然搜索",
    firstContactAt: "2026-06-17T14:00:00Z",
    lastContactAt: "2026-06-17T15:05:00Z",
    totalMessages: 12,
    intentLevel: "medium",
  },
  {
    id: "cus_3",
    name: "留学规划师Lily",
    avatar: "",
    platform: "douyin",
    platformUid: "dy_user_001",
    phone: "137****6666",
    email: "lily@example.com",
    status: "converted",
    leadStatus: "converted",
    tags: ["tag_2", "tag_4", "tag_7"],
    note: "已报名雅思冲刺班，客单价8800",
    source: "直播间咨询",
    firstContactAt: "2026-06-10T09:00:00Z",
    lastContactAt: "2026-06-16T18:00:00Z",
    totalMessages: 56,
    intentLevel: "high",
  },
  {
    id: "cus_4",
    name: "宝妈妈咪",
    avatar: "",
    platform: "xiaohongshu",
    platformUid: "xhs_user_003",
    status: "following",
    leadStatus: "not_leaded",
    tags: ["tag_5", "tag_6"],
    note: "咨询少儿英语启蒙课程",
    source: "笔记评论",
    firstContactAt: "2026-06-16T11:00:00Z",
    lastContactAt: "2026-06-17T13:20:00Z",
    totalMessages: 8,
    intentLevel: "low",
  },
  {
    id: "cus_5",
    name: "考研二战的小王",
    avatar: "",
    platform: "kuaishou",
    platformUid: "ks_user_001",
    phone: "135****2222",
    wechat: "wang_kaoyan",
    status: "following",
    leadStatus: "leaded",
    tags: ["tag_1", "tag_3"],
    note: "二战考生，需要全科辅导，预算充足",
    source: "短视频咨询",
    firstContactAt: "2026-06-14T16:00:00Z",
    lastContactAt: "2026-06-17T12:00:00Z",
    totalMessages: 42,
    intentLevel: "high",
  },
  {
    id: "cus_6",
    name: "迷茫的毕业生",
    avatar: "",
    platform: "douyin",
    platformUid: "dy_user_002",
    status: "new",
    leadStatus: "not_leaded",
    tags: ["tag_6"],
    note: "刚毕业想考公，咨询课程",
    source: "直播间咨询",
    firstContactAt: "2026-06-17T10:00:00Z",
    lastContactAt: "2026-06-17T10:30:00Z",
    totalMessages: 5,
    intentLevel: "unknown",
  },
  {
    id: "cus_7",
    name: "在职考研打工人",
    avatar: "",
    platform: "xiaohongshu",
    platformUid: "xhs_user_004",
    phone: "136****9999",
    status: "converted",
    leadStatus: "converted",
    tags: ["tag_2", "tag_3", "tag_7"],
    note: "已报名在职考研周末班",
    source: "聚光广告-在职考研",
    firstContactAt: "2026-06-08T14:00:00Z",
    lastContactAt: "2026-06-15T20:00:00Z",
    totalMessages: 63,
    intentLevel: "high",
  },
  {
    id: "cus_8",
    name: "雅思7分冲鸭",
    avatar: "",
    platform: "kuaishou",
    platformUid: "ks_user_002",
    status: "following",
    leadStatus: "not_leaded",
    tags: ["tag_4", "tag_6"],
    note: "目标雅思7分，咨询一对一辅导价格",
    source: "短视频评论",
    firstContactAt: "2026-06-17T09:00:00Z",
    lastContactAt: "2026-06-17T11:30:00Z",
    totalMessages: 15,
    intentLevel: "medium",
  },
];

// ===== 会话 =====
export const mockConversations: Conversation[] = [
  {
    id: "conv_1",
    customerId: "cus_1",
    customer: mockCustomers[0],
    accountId: "acc_1",
    account: mockAccounts[0],
    platform: "xiaohongshu",
    status: "active",
    assignedAgentId: "agent_1",
    assignedAgent: mockAgents[0],
    unreadCount: 2,
    lastMessage: "好的，那周末班的上课时间是什么时候呢？",
    lastMessageAt: "2026-06-17T15:10:00Z",
    aiEnabled: true,
    createdAt: "2026-06-15T10:30:00Z",
    messages: [
      {
        id: "msg_1",
        conversationId: "conv_1",
        sender: "customer",
        type: "text",
        content: "你好，我看到你们有考研英语冲刺班，想了解一下",
        createdAt: "2026-06-15T10:30:00Z",
      },
      {
        id: "msg_2",
        conversationId: "conv_1",
        sender: "ai",
        type: "text",
        content: "您好呀~ 很高兴您对考研英语冲刺班感兴趣！我们的冲刺班专为考前3个月集中提分设计，包含真题精讲、作文模板和模拟测试。请问您目前英语大概什么水平呢？这样我可以为您推荐最合适的班型 😊",
        createdAt: "2026-06-15T10:30:30Z",
        isAI: true,
        aiConfidence: 0.95,
      },
      {
        id: "msg_3",
        conversationId: "conv_1",
        sender: "customer",
        type: "text",
        content: "我六级425分，感觉作文和翻译比较弱",
        createdAt: "2026-06-15T10:32:00Z",
      },
      {
        id: "msg_4",
        conversationId: "conv_1",
        sender: "ai",
        type: "text",
        content: "六级425分基础很不错呢！针对您作文和翻译的弱项，我特别推荐我们的「写作翻译专项突破班」，每周3次课，专门训练高分作文框架和翻译技巧。上期学员平均提分15+分。您方便留个微信吗？我把详细课表和试听链接发给您看看~",
        createdAt: "2026-06-15T10:32:30Z",
        isAI: true,
        aiConfidence: 0.92,
      },
      {
        id: "msg_5",
        conversationId: "conv_1",
        sender: "customer",
        type: "text",
        content: "好的，我的微信是 xm_study",
        createdAt: "2026-06-15T10:35:00Z",
      },
      {
        id: "msg_6",
        conversationId: "conv_1",
        sender: "system",
        type: "text",
        content: "AI已自动识别并提取客户微信联系方式，标记为「已留资」",
        createdAt: "2026-06-15T10:35:05Z",
      },
      {
        id: "msg_7",
        conversationId: "conv_1",
        sender: "customer",
        type: "text",
        content: "好的，那周末班的上课时间是什么时候呢？",
        createdAt: "2026-06-17T15:10:00Z",
      },
    ],
  },
  {
    id: "conv_2",
    customerId: "cus_2",
    customer: mockCustomers[1],
    accountId: "acc_2",
    account: mockAccounts[1],
    platform: "xiaohongshu",
    status: "waiting",
    unreadCount: 1,
    lastMessage: "价格多少呀？有没有优惠？",
    lastMessageAt: "2026-06-17T15:05:00Z",
    aiEnabled: true,
    createdAt: "2026-06-17T14:00:00Z",
    messages: [
      {
        id: "msg_8",
        conversationId: "conv_2",
        sender: "customer",
        type: "text",
        content: "考研政治有课吗？",
        createdAt: "2026-06-17T14:00:00Z",
      },
      {
        id: "msg_9",
        conversationId: "conv_2",
        sender: "ai",
        type: "text",
        content: "有的哦~ 我们有考研政治全程班和冲刺班两种。全程班从基础到冲刺全覆盖，冲刺班适合最后阶段提分。现在报名全程班还赠送时政热点手册呢。您是大几的学生呀？",
        createdAt: "2026-06-17T14:00:30Z",
        isAI: true,
        aiConfidence: 0.94,
      },
      {
        id: "msg_10",
        conversationId: "conv_2",
        sender: "customer",
        type: "text",
        content: "价格多少呀？有没有优惠？",
        createdAt: "2026-06-17T15:05:00Z",
      },
    ],
  },
  {
    id: "conv_3",
    customerId: "cus_4",
    customer: mockCustomers[3],
    accountId: "acc_1",
    account: mockAccounts[0],
    platform: "xiaohongshu",
    status: "active",
    assignedAgentId: "agent_1",
    assignedAgent: mockAgents[0],
    unreadCount: 0,
    lastMessage: "我家孩子5岁，适合哪个级别呀？",
    lastMessageAt: "2026-06-17T13:20:00Z",
    aiEnabled: true,
    createdAt: "2026-06-16T11:00:00Z",
    messages: [
      {
        id: "msg_11",
        conversationId: "conv_3",
        sender: "customer",
        type: "text",
        content: "请问有少儿英语启蒙课吗？",
        createdAt: "2026-06-16T11:00:00Z",
      },
      {
        id: "msg_12",
        conversationId: "conv_3",
        sender: "ai",
        type: "text",
        content: "有的呢~ 我们有针对3-8岁的少儿英语启蒙课程，采用沉浸式教学法，外教+中教双师模式。小朋友们在玩中学，效果特别好！请问宝贝多大了呀？",
        createdAt: "2026-06-16T11:00:30Z",
        isAI: true,
        aiConfidence: 0.93,
      },
      {
        id: "msg_13",
        conversationId: "conv_3",
        sender: "customer",
        type: "text",
        content: "我家孩子5岁，适合哪个级别呀？",
        createdAt: "2026-06-17T13:20:00Z",
      },
    ],
  },
  {
    id: "conv_4",
    customerId: "cus_6",
    customer: mockCustomers[5],
    accountId: "acc_3",
    account: mockAccounts[2],
    platform: "douyin",
    status: "waiting",
    unreadCount: 3,
    lastMessage: "公务员考试有什么课程推荐吗？",
    lastMessageAt: "2026-06-17T10:30:00Z",
    aiEnabled: false,
    createdAt: "2026-06-17T10:00:00Z",
    messages: [
      {
        id: "msg_14",
        conversationId: "conv_4",
        sender: "customer",
        type: "text",
        content: "公务员考试有什么课程推荐吗？",
        createdAt: "2026-06-17T10:30:00Z",
      },
    ],
  },
  {
    id: "conv_5",
    customerId: "cus_8",
    customer: mockCustomers[7],
    accountId: "acc_5",
    account: mockAccounts[4],
    platform: "kuaishou",
    status: "active",
    assignedAgentId: "agent_4",
    assignedAgent: mockAgents[3],
    unreadCount: 0,
    lastMessage: "一对一辅导一小时多少钱？",
    lastMessageAt: "2026-06-17T11:30:00Z",
    aiEnabled: true,
    createdAt: "2026-06-17T09:00:00Z",
    messages: [
      {
        id: "msg_15",
        conversationId: "conv_5",
        sender: "customer",
        type: "text",
        content: "想考雅思7分，有一对一辅导吗？",
        createdAt: "2026-06-17T09:00:00Z",
      },
      {
        id: "msg_16",
        conversationId: "conv_5",
        sender: "ai",
        type: "text",
        content: "当然有！我们的雅思一对一辅导由前考官团队执教，针对您的薄弱项定制学习方案。目标7分的话，通常建议60-80课时。请问您目前雅思大概什么水平？之前考过吗？",
        createdAt: "2026-06-17T09:00:30Z",
        isAI: true,
        aiConfidence: 0.91,
      },
      {
        id: "msg_17",
        conversationId: "conv_5",
        sender: "customer",
        type: "text",
        content: "一对一辅导一小时多少钱？",
        createdAt: "2026-06-17T11:30:00Z",
      },
    ],
  },
];

// ===== 评论 =====
export const mockComments: Comment[] = [
  {
    id: "cmt_1",
    accountId: "acc_1",
    account: mockAccounts[0],
    postId: "post_001",
    postTitle: "考研英语80+上岸经验分享｜时间规划篇",
    postCover: "",
    customerName: "考研人小李",
    customerAvatar: "",
    content: "请问冲刺班什么时候开课呀？想报名！",
    status: "pending",
    hasHighIntent: true,
    createdAt: "2026-06-17T15:00:00Z",
  },
  {
    id: "cmt_2",
    accountId: "acc_1",
    account: mockAccounts[0],
    postId: "post_001",
    postTitle: "考研英语80+上岸经验分享｜时间规划篇",
    postCover: "",
    customerName: "上岸学姐",
    customerAvatar: "",
    content: "跟着你们的课上岸了，感谢！",
    status: "replied",
    reply: "太棒啦！恭喜上岸！🎉",
    hasHighIntent: false,
    createdAt: "2026-06-17T14:30:00Z",
  },
  {
    id: "cmt_3",
    accountId: "acc_3",
    account: mockAccounts[2],
    postId: "post_002",
    postTitle: "【直播回放】雅思口语7分技巧大公开",
    postCover: "",
    customerName: "雅思考鸭",
    customerAvatar: "",
    content: "一对一怎么收费？急求！",
    status: "pending",
    hasHighIntent: true,
    createdAt: "2026-06-17T13:45:00Z",
  },
  {
    id: "cmt_4",
    accountId: "acc_2",
    account: mockAccounts[1],
    postId: "post_003",
    postTitle: "考研政治时政热点汇总（2026最新）",
    postCover: "",
    customerName: "政治小白",
    customerAvatar: "",
    content: "这个时政资料可以私信发我一份吗？",
    status: "pending",
    hasHighIntent: true,
    createdAt: "2026-06-17T12:00:00Z",
  },
  {
    id: "cmt_5",
    accountId: "acc_3",
    account: mockAccounts[2],
    postId: "post_002",
    postTitle: "【直播回放】雅思口语7分技巧大公开",
    postCover: "",
    customerName: "英语爱好者",
    customerAvatar: "",
    content: "老师讲得真好，学到了！",
    status: "ignored",
    hasHighIntent: false,
    createdAt: "2026-06-17T11:00:00Z",
  },
  {
    id: "cmt_6",
    accountId: "acc_5",
    account: mockAccounts[4],
    postId: "post_004",
    postTitle: "留学申请时间线规划｜干货满满",
    postCover: "",
    customerName: "准备出国的小张",
    customerAvatar: "",
    content: "请问你们提供留学申请全程服务吗？价格多少？",
    status: "pending",
    hasHighIntent: true,
    createdAt: "2026-06-17T10:30:00Z",
  },
];

// ===== 知识库分类 =====
export const mockKnowledgeCategories: KnowledgeCategory[] = [
  {
    id: "cat_1",
    name: "课程介绍",
    description: "所有课程的产品信息、价格、课表等",
    documentCount: 45,
    icon: "BookOpen",
  },
  {
    id: "cat_2",
    name: "常见问题",
    description: "客户高频问题及标准回答",
    documentCount: 128,
    icon: "HelpCircle",
  },
  {
    id: "cat_3",
    name: "销售话术",
    description: "各场景转化话术模板",
    documentCount: 36,
    icon: "MessageSquare",
  },
  {
    id: "cat_4",
    name: "退费政策",
    description: "退费流程、规则及注意事项",
    documentCount: 12,
    icon: "FileText",
  },
  {
    id: "cat_5",
    name: "活动促销",
    description: "正在进行和即将开始的优惠活动",
    documentCount: 18,
    icon: "Tag",
  },
  {
    id: "cat_6",
    name: "行业知识",
    description: "考研、留学、K12等领域的专业知识库",
    documentCount: 89,
    icon: "GraduationCap",
  },
];

// ===== 知识库文档 =====
export const mockKnowledgeDocuments: KnowledgeDocument[] = [
  {
    id: "doc_1",
    categoryId: "cat_1",
    title: "考研英语冲刺班 - 产品介绍",
    content: "考研英语冲刺班专为考前3个月集中提分设计...",
    source: "手动录入",
    status: "active",
    updatedAt: "2026-06-15T10:00:00Z",
    chunkCount: 8,
    hitCount: 342,
  },
  {
    id: "doc_2",
    categoryId: "cat_1",
    title: "雅思一对一辅导 - 收费标准",
    content: "雅思一对一辅导收费：前考官团队300元/课时...",
    source: "文件上传",
    status: "active",
    updatedAt: "2026-06-14T14:00:00Z",
    chunkCount: 5,
    hitCount: 189,
  },
  {
    id: "doc_3",
    categoryId: "cat_2",
    title: "Q: 课程可以试听吗？",
    content: "A: 当然可以！我们提供免费试听课...",
    source: "手动录入",
    status: "active",
    updatedAt: "2026-06-16T09:00:00Z",
    chunkCount: 3,
    hitCount: 567,
  },
  {
    id: "doc_4",
    categoryId: "cat_3",
    title: "留资引导话术 - 高意向客户",
    content: "针对已表达明确意向的客户，采用自然引导方式...",
    source: "AI生成",
    status: "active",
    updatedAt: "2026-06-17T11:00:00Z",
    chunkCount: 6,
    hitCount: 234,
  },
  {
    id: "doc_5",
    categoryId: "cat_4",
    title: "退费政策总则",
    content: "开课前退费全额退款，开课后按已上课时比例退款...",
    source: "文件上传",
    status: "active",
    updatedAt: "2026-06-10T16:00:00Z",
    chunkCount: 4,
    hitCount: 78,
  },
  {
    id: "doc_6",
    categoryId: "cat_5",
    title: "暑期大促活动方案",
    content: "6月20日-7月31日，所有课程8折优惠...",
    source: "手动录入",
    status: "training",
    updatedAt: "2026-06-17T08:00:00Z",
    chunkCount: 7,
    hitCount: 0,
  },
];

// ===== AI员工列表 =====
export const mockAIAgents: AIAgent[] = [
  {
    id: "agent_xiaozhi",
    name: "小智",
    template: "active_lead",
    avatar: "小",
    status: "enabled",
    boundChannels: [
      { platform: "xiaohongshu", accountName: "抱熊腰课程家", accountId: "acc_1" },
      { platform: "douyin", accountName: "DMT克抖", accountId: "acc_2" },
    ],
    createdAt: "2026-06-04T14:09:25Z",
    updatedAt: "2026-06-04T14:09:25Z",
    scope: {
      channels: [
        { platform: "xiaohongshu", accountName: "抱熊腰课程家", accountId: "acc_1" },
        { platform: "douyin", accountName: "DMT克抖", accountId: "acc_2" },
      ],
      serviceMode: "all_day",
      expertise: "",
    },
    style: {
      greeting: "请输入开场白内容",
      defaultTone: "",
      toneConstraint: "",
      checkWechat: false,
      wechatReplacement: "",
      checkPhone: false,
      phoneReplacement: "",
    },
    pauseRule: {
      satisfactionEnabled: false,
      keywordEnabled: false,
      pauseKeywords: [],
      platformStrategyEnabled: false,
      xiaohongshuDelay: 60,
      douyinDelay: 60,
    },
    replyConfig: {
      maxLength: "medium",
      aggregateWindow: 0,
      delayedReplyInterval: 0,
    },
    skills: [
      { type: "lead", name: "获客", description: "收集顾客信息", enabled: false, hasWarning: true },
      { type: "self_learn", name: "服务", description: "在有疑问的时候回复联系方式", enabled: true },
      { type: "auto_reply", name: "页脚追问", description: "当顾客页脚时主动追问", enabled: true },
    ],
    learning: {
      companyIntro: "",
      productIntro: "",
      serviceAudience: "",
      businessKnowledge: "",
    },
  },
  {
    id: "agent_dmt",
    name: "DMT-朱朱",
    template: "active_lead",
    avatar: "朱",
    status: "disabled",
    boundChannels: [],
    createdAt: "2026-06-04T14:09:25Z",
    updatedAt: "2026-06-04T14:09:25Z",
    scope: {
      channels: [],
      serviceMode: "all_day",
      expertise: "一个活泼鄒小女孩的助手",
    },
    style: {
      greeting: "",
      defaultTone: "",
      toneConstraint: "",
      checkWechat: false,
      wechatReplacement: "",
      checkPhone: false,
      phoneReplacement: "",
    },
    pauseRule: {
      satisfactionEnabled: false,
      keywordEnabled: false,
      pauseKeywords: [],
      platformStrategyEnabled: false,
      xiaohongshuDelay: 60,
      douyinDelay: 60,
    },
    replyConfig: {
      maxLength: "medium",
      aggregateWindow: 0,
      delayedReplyInterval: 0,
    },
    skills: [],
    learning: {
      companyIntro: "",
      productIntro: "",
      serviceAudience: "",
      businessKnowledge: "",
    },
  },
  {
    id: "agent_shuzi",
    name: "数字化",
    template: "active_lead",
    avatar: "数",
    status: "disabled",
    boundChannels: [],
    createdAt: "2026-06-04T14:09:25Z",
    updatedAt: "2026-06-04T14:09:25Z",
    scope: {
      channels: [],
      serviceMode: "all_day",
      expertise: "一个资深顾问",
    },
    style: {
      greeting: "",
      defaultTone: "",
      toneConstraint: "",
      checkWechat: false,
      wechatReplacement: "",
      checkPhone: false,
      phoneReplacement: "",
    },
    pauseRule: {
      satisfactionEnabled: false,
      keywordEnabled: false,
      pauseKeywords: [],
      platformStrategyEnabled: false,
      xiaohongshuDelay: 60,
      douyinDelay: 60,
    },
    replyConfig: {
      maxLength: "medium",
      aggregateWindow: 0,
      delayedReplyInterval: 0,
    },
    skills: [],
    learning: {
      companyIntro: "",
      productIntro: "",
      serviceAudience: "",
      businessKnowledge: "",
    },
  },
  {
    id: "agent_diqu",
    name: "地渠道AI",
    template: "card_lead",
    avatar: "地",
    status: "enabled",
    boundChannels: [
      { platform: "xiaohongshu", accountName: "抱熊腰课程家", accountId: "acc_1" },
      { platform: "xiaohongshu", accountName: "抱熊腰", accountId: "acc_3" },
      { platform: "weixin", accountName: "77", accountId: "acc_4" },
    ],
    createdAt: "2026-06-12T15:40:30Z",
    updatedAt: "2026-06-12T15:40:30Z",
    scope: {
      channels: [
        { platform: "xiaohongshu", accountName: "抱熊腰课程家", accountId: "acc_1" },
        { platform: "xiaohongshu", accountName: "抱熊腰", accountId: "acc_3" },
        { platform: "weixin", accountName: "77", accountId: "acc_4" },
      ],
      serviceMode: "all_day",
      expertise: "",
    },
    style: {
      greeting: "请输入开场白内容",
      defaultTone: "",
      toneConstraint: "",
      checkWechat: false,
      wechatReplacement: "",
      checkPhone: false,
      phoneReplacement: "",
    },
    pauseRule: {
      satisfactionEnabled: false,
      keywordEnabled: false,
      pauseKeywords: [],
      platformStrategyEnabled: false,
      xiaohongshuDelay: 60,
      douyinDelay: 60,
    },
    replyConfig: {
      maxLength: "medium",
      aggregateWindow: 0,
      delayedReplyInterval: 0,
    },
    skills: [
      { type: "lead", name: "获客", description: "在有疑问的时候回复联系方式", enabled: true },
      { type: "self_learn", name: "服务", description: "微信人设、背景信息、相关知识，解答顾客问题并留资", enabled: true },
    ],
    learning: {
      companyIntro: "",
      productIntro: "",
      serviceAudience: "",
      businessKnowledge: "",
    },
  },
  {
    id: "agent_xiaoxi",
    name: "小希",
    template: "precise_lead",
    avatar: "希",
    status: "enabled",
    boundChannels: [
      { platform: "xiaohongshu", accountName: "中明框", accountId: "acc_5" },
      { platform: "xiaohongshu", accountName: "中明框官", accountId: "acc_6" },
      { platform: "xiaohongshu", accountName: "中明框·心", accountId: "acc_7" },
    ],
    createdAt: "2026-06-15T16:58:00Z",
    updatedAt: "2026-06-15T16:58:00Z",
    scope: {
      channels: [
        { platform: "xiaohongshu", accountName: "中明框", accountId: "acc_5" },
        { platform: "xiaohongshu", accountName: "中明框官", accountId: "acc_6" },
        { platform: "xiaohongshu", accountName: "中明框·心", accountId: "acc_7" },
      ],
      serviceMode: "all_day",
      expertise: "中明框·心",
    },
    style: {
      greeting: "请输入开场白内容",
      defaultTone: "",
      toneConstraint: "",
      checkWechat: false,
      wechatReplacement: "",
      checkPhone: false,
      phoneReplacement: "",
    },
    pauseRule: {
      satisfactionEnabled: false,
      keywordEnabled: false,
      pauseKeywords: [],
      platformStrategyEnabled: false,
      xiaohongshuDelay: 60,
      douyinDelay: 60,
    },
    replyConfig: {
      maxLength: "medium",
      aggregateWindow: 0,
      delayedReplyInterval: 0,
    },
    skills: [],
    learning: {
      companyIntro: "",
      productIntro: "",
      serviceAudience: "",
      businessKnowledge: "",
    },
  },
];

// ===== AI配置 =====
export const defaultAIConfig: AIConfig = {
  model: "deepseek-chat",
  apiKey: "sk-****************************",
  apiBaseUrl: "https://api.deepseek.com/v1",
  temperature: 0.7,
  maxTokens: 1024,
  systemPrompt: `你是一位专业的教育机构客服代表，名叫"小智"。你的职责是：
1. 热情专业地回答客户关于课程的问题
2. 自然地引导客户留下联系方式（微信/手机号），不要生硬要
3. 根据客户需求推荐最合适的课程
4. 保持亲切友好的语气，适当使用emoji
5. 遇到超出知识库范围的问题，诚实告知并转接人工客服
请始终保持"以人为本"的服务理念，避免使用过于推销的话术。`,
  welcomeMessage: "您好呀~ 我是智客教育的AI课程顾问小智，有什么可以帮到您的吗？😊",
  tone: "friendly",
  antiAdEnabled: true,
  autoReplyEnabled: true,
  autoReplyDelay: 3,
  intentRecognitionEnabled: true,
  selfEvolutionEnabled: true,
  fallbackToHuman: true,
  fallbackThreshold: 0.6,
  maxConversationTurns: 15,
  knowledgeCategoryIds: ["cat_1", "cat_2", "cat_3"],
  proactivelyMessage: true,
  extractContactEnabled: true,
  emotionAnalysisEnabled: true,
};

// ===== 话术模板 =====
export const mockScriptTemplates: ScriptTemplate[] = [
  {
    id: "script_1",
    name: "开场问候",
    scenario: "新会话开始",
    trigger: "客户首次发消息",
    content: "您好呀~ 很高兴见到您！我是智客教育的课程顾问小智，有什么可以帮到您的吗？😊",
    enabled: true,
    hitCount: 1280,
    conversionRate: 0.32,
    category: "greeting",
    priority: 1,
  },
  {
    id: "script_2",
    name: "留资引导-高意向",
    scenario: "客户表达明确购买意向",
    trigger: "客户询问价格/课程详情/报名方式",
    content: "看您对我们的课程很感兴趣呢！方便留个微信吗？我把详细的课表、试听视频和优惠信息发给您看看~",
    enabled: true,
    hitCount: 456,
    conversionRate: 0.68,
    category: "lead",
    priority: 1,
  },
  {
    id: "script_3",
    name: "留资引导-中意向",
    scenario: "客户在了解阶段",
    trigger: "客户询问2-3个问题后",
    content: "对了，我们最近刚好有个免费的试听课活动，我可以帮您预约一下。您方便留个手机号吗？试听链接会直接发到您手机上~",
    enabled: true,
    hitCount: 623,
    conversionRate: 0.41,
    category: "lead",
    priority: 2,
  },
  {
    id: "script_4",
    name: "价格异议处理",
    scenario: "客户觉得价格贵",
    trigger: "客户表达价格担忧",
    content: "理解您的顾虑~ 我们的价格在同行中其实性价比很高哦。而且现在报名还能享受暑期8折优惠，算下来每课时才XX元。另外我们支持分期付款，完全没有压力呢！",
    enabled: true,
    hitCount: 234,
    conversionRate: 0.35,
    category: "objection",
    priority: 1,
  },
  {
    id: "script_5",
    name: "转人工客服",
    scenario: "AI无法处理的问题",
    trigger: "置信度低于阈值/客户要求人工",
    content: "这个问题比较复杂，我帮您转接给我们的资深课程顾问，请稍等一下哦~",
    enabled: true,
    hitCount: 89,
    conversionRate: 0.72,
    category: "fallback",
    priority: 1,
  },
  {
    id: "script_6",
    name: "结束语-已留资",
    scenario: "客户已留资",
    trigger: "客户留下联系方式",
    content: "收到啦！我这边马上安排顾问老师联系您，一般1小时内就会加您微信哦，请留意一下好友申请~ 期待为您服务！",
    enabled: true,
    hitCount: 312,
    conversionRate: 0.95,
    category: "closing",
    priority: 1,
  },
  {
    id: "script_7",
    name: "跟进回访-未回复",
    scenario: "客户超过24小时未回复",
    trigger: "上次对话超过24小时无回应",
    content: "嗨~ 昨天和您聊的课程方面还有什么疑问吗？我们这周刚好有新的试听名额开放，需要帮您留一个吗？😄",
    enabled: false,
    hitCount: 156,
    conversionRate: 0.18,
    category: "followup",
    priority: 3,
  },
  {
    id: "script_8",
    name: "竞品对比异议",
    scenario: "客户提到竞品",
    trigger: "客户提及其他机构名称",
    content: "每家机构都有自己的特色呢~ 相比之下，我们的优势在于：1️⃣ 师资全部985/211硕士起步 2️⃣ 小班教学，每班不超过8人 3️⃣ 不满意随时退费。要不我发份详细对比表给您看看？",
    enabled: true,
    hitCount: 178,
    conversionRate: 0.29,
    category: "objection",
    priority: 2,
  },
];

// ===== 仪表盘数据 =====
export const mockDashboardStats: DashboardStats = {
  totalConversations: 3428,
  activeConversations: 28,
  aiHandledRate: 0.873,
  leadConversionRate: 0.342,
  avgResponseTime: 2.8,
  totalLeads: 1172,
  totalCustomers: 8654,
  aiPointBalance: 45680,
  conversationTrend: Array.from({ length: 14 }, (_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (13 - i));
    return {
      date: `${date.getMonth() + 1}/${date.getDate()}`,
      count: Math.floor(200 + Math.random() * 150),
      aiCount: Math.floor(170 + Math.random() * 130),
    };
  }),
  platformDistribution: [
    { platform: "xiaohongshu" as Platform, count: 1856, leadRate: 0.38 },
    { platform: "douyin" as Platform, count: 982, leadRate: 0.29 },
    { platform: "kuaishou" as Platform, count: 412, leadRate: 0.31 },
    { platform: "weixin" as Platform, count: 178, leadRate: 0.45 },
  ],
  hourlyDistribution: Array.from({ length: 24 }, (_, h) => ({
    hour: `${h}:00`,
    count: Math.floor(
      (h >= 8 && h <= 23 ? 80 + Math.random() * 120 : Math.random() * 30)
    ),
  })),
  topAgents: [
    { agent: mockAgents[0], conversations: 342, leads: 128, satisfaction: 0.96 },
    { agent: mockAgents[1], conversations: 298, leads: 102, satisfaction: 0.94 },
    { agent: mockAgents[3], conversations: 256, leads: 89, satisfaction: 0.92 },
    { agent: mockAgents[2], conversations: 234, leads: 76, satisfaction: 0.89 },
  ],
};
